USE [master]
GO

/****** Object:  Database [GO_Proyecto]    Script Date: 2/4/2024 08:53:31 ******/
CREATE DATABASE [GO_Proyecto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GO_Proyecto', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GO_Proyecto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GO_Proyecto_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GO_Proyecto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GO_Proyecto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GO_Proyecto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GO_Proyecto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GO_Proyecto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GO_Proyecto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GO_Proyecto] SET ARITHABORT OFF 
GO

ALTER DATABASE [GO_Proyecto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GO_Proyecto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GO_Proyecto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GO_Proyecto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GO_Proyecto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GO_Proyecto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GO_Proyecto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GO_Proyecto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GO_Proyecto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GO_Proyecto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GO_Proyecto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GO_Proyecto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GO_Proyecto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GO_Proyecto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GO_Proyecto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GO_Proyecto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GO_Proyecto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GO_Proyecto] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GO_Proyecto] SET  MULTI_USER 
GO

ALTER DATABASE [GO_Proyecto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GO_Proyecto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GO_Proyecto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GO_Proyecto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GO_Proyecto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GO_Proyecto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GO_Proyecto] SET QUERY_STORE = ON
GO

ALTER DATABASE [GO_Proyecto] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [GO_Proyecto] SET  READ_WRITE 
GO

